################################################################
# Practical Binary Code Similarity Detection                   #
#   with BERT-based Transferable Similarity Learning           #
#   (In the 38th Annual Computer Security                      #
#    Applications Conference (ACSAC)                           #
#                                                              #
#  Author: Sunwoo Ahn <swahn@sor.snu.ac.kr>                    #
#          Dept. of Electrical and Computer Engineering        #
#            @ Seoul National University                       #
#          Hyungjoon Koo <kevin.koo@skku.edu>                  #
#          Dept. of Computer Science and Engineering           #
#            @ Sungkyunkwan University                         #
#                                                              #
#  This file can be distributed under the MIT License.         #
#  See the LICENSE file for details.                           #
################################################################

# https://www.gnu.org/software/libc/manual/html_node/Function-Index.html
function_list = {
    "_exit": "Termination Internals",
    "_Exit": "Termination Internals",
    "_flushlbf": "Flushing Buffers",
    "_tolower": "Case Conversion",
    "_toupper": "Case Conversion",
    "__fbufsize": "Controlling Buffering",
    "__flbf": "Controlling Buffering",
    "__fpending": "Controlling Buffering",
    "__fpurge": "Flushing Buffers",
    "__freadable": "Opening Streams",
    "__freading": "Opening Streams",
    "__fsetlocking": "Streams and Threads",
    "__fwritable": "Opening Streams",
    "__fwriting": "Opening Streams",
    "__ppc_get_timebase": "PowerPC",
    "__ppc_get_timebase_freq": "PowerPC",
    "__ppc_mdoio": "PowerPC",
    "__ppc_mdoom": "PowerPC",
    "__ppc_set_ppr_low": "PowerPC",
    "__ppc_set_ppr_med": "PowerPC",
    "__ppc_set_ppr_med_high": "PowerPC",
    "__ppc_set_ppr_med_low": "PowerPC",
    "__ppc_set_ppr_very_low": "PowerPC",
    "__ppc_yield": "PowerPC",
    "__riscv_flush_icache": "RISC-V",
    "__va_copy": "Argument Macros",
    "a64l": "Encode Binary Data",
    "abort": "Aborting a Program",
    "abs": "Absolute Value",
    "accept": "Accepting Connections",
    "access": "Testing File Access",
    "acos": "Inverse Trig Functions",
    "acosf": "Inverse Trig Functions",
    "acosfN": "Inverse Trig Functions",
    "acosfNx": "Inverse Trig Functions",
    "acosh": "Hyperbolic Functions",
    "acoshf": "Hyperbolic Functions",
    "acoshfN": "Hyperbolic Functions",
    "acoshfNx": "Hyperbolic Functions",
    "acoshl": "Hyperbolic Functions",
    "acosl": "Inverse Trig Functions",
    "addmntent": "mtab",
    "addseverity": "Adding Severity Classes",
    "adjtime": "Setting and Adjusting the Time",
    "adjtimex": "Setting and Adjusting the Time",
    "aio_cancel": "Cancel AIO Operations",
    "aio_cancel64": "Cancel AIO Operations",
    "aio_error": "Status of AIO Operations",
    "aio_error64": "Status of AIO Operations",
    "aio_fsync": "Synchronizing AIO Operations",
    "aio_fsync64": "Synchronizing AIO Operations",
    "aio_init": "Configuration of AIO",
    "aio_read": "Asynchronous Reads/Writes",
    "aio_read64": "Asynchronous Reads/Writes",
    "aio_return": "Status of AIO Operations",
    "aio_return64": "Status of AIO Operations",
    "aio_suspend": "Synchronizing AIO Operations",
    "aio_suspend64": "Synchronizing AIO Operations",
    "aio_write": "Asynchronous Reads/Writes",
    "aio_write64": "Asynchronous Reads/Writes",
    "alarm": "Setting an Alarm",
    "aligned_alloc": "Aligned Memory Blocks",
    "alloca": "Variable Size Automatic",
    "alphasort": "Scanning Directory Content",
    "alphasort64": "Scanning Directory Content",
    "argp_error": "Argp Helper Functions",
    "argp_failure": "Argp Helper Functions",
    "argp_help": "Argp Help",
    "argp_parse": "Argp",
    "argp_state_help": "Argp Helper Functions",
    "argp_usage": "Argp Helper Functions",
    "argz_add": "Argz Functions",
    "argz_add_sep": "Argz Functions",
    "argz_append": "Argz Functions",
    "argz_count": "Argz Functions",
    "argz_create": "Argz Functions",
    "argz_create_sep": "Argz Functions",
    "argz_delete": "Argz Functions",
    "argz_extract": "Argz Functions",
    "argz_insert": "Argz Functions",
    "argz_next": "Argz Functions",
    "argz_replace": "Argz Functions",
    "argz_stringify": "Argz Functions",
    "asctime": "Formatting Calendar Time",
    "asctime_r": "Formatting Calendar Time",
    "asin": "Inverse Trig Functions",
    "asinf": "Inverse Trig Functions",
    "asinfN": "Inverse Trig Functions",
    "asinfNx": "Inverse Trig Functions",
    "asinh": "Hyperbolic Functions",
    "asinhf": "Hyperbolic Functions",
    "asinhfN": "Hyperbolic Functions",
    "asinhfNx": "Hyperbolic Functions",
    "asinhl": "Hyperbolic Functions",
    "asinl": "Inverse Trig Functions",
    "asprintf": "Dynamic Output",
    "assert": "Consistency Checking",
    "assert_perror": "Consistency Checking",
    "atan": "Inverse Trig Functions",
    "atan2": "Inverse Trig Functions",
    "atan2f": "Inverse Trig Functions",
    "atan2fN": "Inverse Trig Functions",
    "atan2fNx": "Inverse Trig Functions",
    "atan2l": "Inverse Trig Functions",
    "atanf": "Inverse Trig Functions",
    "atanfN": "Inverse Trig Functions",
    "atanfNx": "Inverse Trig Functions",
    "atanh": "Hyperbolic Functions",
    "atanhf": "Hyperbolic Functions",
    "atanhfN": "Hyperbolic Functions",
    "atanhfNx": "Hyperbolic Functions",
    "atanhl": "Hyperbolic Functions",
    "atanl": "Inverse Trig Functions",
    "atexit": "Cleanups on Exit",
    "atof": "Parsing of Floats",
    "atoi": "Parsing of Integers",
    "atol": "Parsing of Integers",
    "atoll": "Parsing of Integers",
    "backtrace": "Backtraces",
    "backtrace_symbols": "Backtraces",
    "backtrace_symbols_fd": "Backtraces",
    "basename": "Finding Tokens in a String",
    "basename": "Finding Tokens in a String",
    "bcmp": "String/Array Comparison",
    "bcopy": "Copying Strings and Arrays",
    "bind": "Setting Address",
    "bindtextdomain": "Locating gettext catalog",
    "bind_textdomain_codeset": "Charset conversion in gettext",
    "brk": "Resizing the Data Segment",
    "bsearch": "Array Search Function",
    "btowc": "Converting a Character",
    "bzero": "Copying Strings and Arrays",
    "cabs": "Absolute Value",
    "cabsf": "Absolute Value",
    "cabsfN": "Absolute Value",
    "cabsfNx": "Absolute Value",
    "cabsl": "Absolute Value",
    "cacos": "Inverse Trig Functions",
    "cacosf": "Inverse Trig Functions",
    "cacosfN": "Inverse Trig Functions",
    "cacosfNx": "Inverse Trig Functions",
    "cacosh": "Hyperbolic Functions",
    "cacoshf": "Hyperbolic Functions",
    "cacoshfN": "Hyperbolic Functions",
    "cacoshfNx": "Hyperbolic Functions",
    "cacoshl": "Hyperbolic Functions",
    "cacosl": "Inverse Trig Functions",
    "calloc": "Allocating Cleared Space",
    "call_once": "Call Once",
    "canonicalize": "FP Bit Twiddling",
    "canonicalizef": "FP Bit Twiddling",
    "canonicalizefN": "FP Bit Twiddling",
    "canonicalizefNx": "FP Bit Twiddling",
    "canonicalizel": "FP Bit Twiddling",
    "canonicalize_file_name": "Symbolic Links",
    "carg": "Operations on Complex",
    "cargf": "Operations on Complex",
    "cargfN": "Operations on Complex",
    "cargfNx": "Operations on Complex",
    "cargl": "Operations on Complex",
    "casin": "Inverse Trig Functions",
    "casinf": "Inverse Trig Functions",
    "casinfN": "Inverse Trig Functions",
    "casinfNx": "Inverse Trig Functions",
    "casinh": "Hyperbolic Functions",
    "casinhf": "Hyperbolic Functions",
    "casinhfN": "Hyperbolic Functions",
    "casinhfNx": "Hyperbolic Functions",
    "casinhl": "Hyperbolic Functions",
    "casinl": "Inverse Trig Functions",
    "catan": "Inverse Trig Functions",
    "catanf": "Inverse Trig Functions",
    "catanfN": "Inverse Trig Functions",
    "catanfNx": "Inverse Trig Functions",
    "catanh": "Hyperbolic Functions",
    "catanhf": "Hyperbolic Functions",
    "catanhfN": "Hyperbolic Functions",
    "catanhfNx": "Hyperbolic Functions",
    "catanhl": "Hyperbolic Functions",
    "catanl": "Inverse Trig Functions",
    "catclose": "The catgets Functions",
    "catgets": "The catgets Functions",
    "catopen": "The catgets Functions",
    "cbrt": "Exponents and Logarithms",
    "cbrtf": "Exponents and Logarithms",
    "cbrtfN": "Exponents and Logarithms",
    "cbrtfNx": "Exponents and Logarithms",
    "cbrtl": "Exponents and Logarithms",
    "ccos": "Trig Functions",
    "ccosf": "Trig Functions",
    "ccosfN": "Trig Functions",
    "ccosfNx": "Trig Functions",
    "ccosh": "Hyperbolic Functions",
    "ccoshf": "Hyperbolic Functions",
    "ccoshfN": "Hyperbolic Functions",
    "ccoshfNx": "Hyperbolic Functions",
    "ccoshl": "Hyperbolic Functions",
    "ccosl": "Trig Functions",
    "ceil": "Rounding Functions",
    "ceilf": "Rounding Functions",
    "ceilfN": "Rounding Functions",
    "ceilfNx": "Rounding Functions",
    "ceill": "Rounding Functions",
    "cexp": "Exponents and Logarithms",
    "cexpf": "Exponents and Logarithms",
    "cexpfN": "Exponents and Logarithms",
    "cexpfNx": "Exponents and Logarithms",
    "cexpl": "Exponents and Logarithms",
    "cfgetispeed": "Line Speed",
    "cfgetospeed": "Line Speed",
    "cfmakeraw": "Noncanonical Input",
    "cfsetispeed": "Line Speed",
    "cfsetospeed": "Line Speed",
    "cfsetspeed": "Line Speed",
    "chdir": "Working Directory",
    "chmod": "Setting Permissions",
    "chmod": "Setting Permissions",
    "chown": "File Owner",
    "cimag": "Operations on Complex",
    "cimagf": "Operations on Complex",
    "cimagfN": "Operations on Complex",
    "cimagfNx": "Operations on Complex",
    "cimagl": "Operations on Complex",
    "clearenv": "Environment Access",
    "clearerr": "Error Recovery",
    "clearerr_unlocked": "Error Recovery",
    "clock": "CPU Time",
    "clock_getres": "Getting the Time",
    "clock_gettime": "Getting the Time",
    "clock_settime": "Setting and Adjusting the Time",
    "clog": "Exponents and Logarithms",
    "clog10": "Exponents and Logarithms",
    "clog10f": "Exponents and Logarithms",
    "clog10fN": "Exponents and Logarithms",
    "clog10fNx": "Exponents and Logarithms",
    "clog10l": "Exponents and Logarithms",
    "clogf": "Exponents and Logarithms",
    "clogfN": "Exponents and Logarithms",
    "clogfNx": "Exponents and Logarithms",
    "clogl": "Exponents and Logarithms",
    "close": "Opening and Closing Files",
    "closedir": "Reading/Closing Directory",
    "closelog": "closelog",
    "cnd_broadcast": "ISO C Condition Variables",
    "cnd_destroy": "ISO C Condition Variables",
    "cnd_init": "ISO C Condition Variables",
    "cnd_signal": "ISO C Condition Variables",
    "cnd_timedwait": "ISO C Condition Variables",
    "cnd_wait": "ISO C Condition Variables",
    "confstr": "String Parameters",
    "conj": "Operations on Complex",
    "conjf": "Operations on Complex",
    "conjfN": "Operations on Complex",
    "conjfNx": "Operations on Complex",
    "conjl": "Operations on Complex",
    "connect": "Connecting",
    "continue": "Actions in the NSS configuration",
    "copysign": "FP Bit Twiddling",
    "copysignf": "FP Bit Twiddling",
    "copysignfN": "FP Bit Twiddling",
    "copysignfNx": "FP Bit Twiddling",
    "copysignl": "FP Bit Twiddling",
    "copy_file_range": "Copying File Data",
    "cos": "Trig Functions",
    "cosf": "Trig Functions",
    "cosfN": "Trig Functions",
    "cosfNx": "Trig Functions",
    "cosh": "Hyperbolic Functions",
    "coshf": "Hyperbolic Functions",
    "coshfN": "Hyperbolic Functions",
    "coshfNx": "Hyperbolic Functions",
    "coshl": "Hyperbolic Functions",
    "cosl": "Trig Functions",
    "cpow": "Exponents and Logarithms",
    "cpowf": "Exponents and Logarithms",
    "cpowfN": "Exponents and Logarithms",
    "cpowfNx": "Exponents and Logarithms",
    "cpowl": "Exponents and Logarithms",
    "cproj": "Operations on Complex",
    "cprojf": "Operations on Complex",
    "cprojfN": "Operations on Complex",
    "cprojfNx": "Operations on Complex",
    "cprojl": "Operations on Complex",
    "CPU_CLR": "CPU Affinity",
    "CPU_ISSET": "CPU Affinity",
    "CPU_SET": "CPU Affinity",
    "CPU_ZERO": "CPU Affinity",
    "creal": "Operations on Complex",
    "crealf": "Operations on Complex",
    "crealfN": "Operations on Complex",
    "crealfNx": "Operations on Complex",
    "creall": "Operations on Complex",
    "creat": "Opening and Closing Files",
    "creat64": "Opening and Closing Files",
    "crypt": "Passphrase Storage",
    "crypt_r": "Passphrase Storage",
    "csin": "Trig Functions",
    "csinf": "Trig Functions",
    "csinfN": "Trig Functions",
    "csinfNx": "Trig Functions",
    "csinh": "Hyperbolic Functions",
    "csinhf": "Hyperbolic Functions",
    "csinhfN": "Hyperbolic Functions",
    "csinhfNx": "Hyperbolic Functions",
    "csinhl": "Hyperbolic Functions",
    "csinl": "Trig Functions",
    "csqrt": "Exponents and Logarithms",
    "csqrtf": "Exponents and Logarithms",
    "csqrtfN": "Exponents and Logarithms",
    "csqrtfNx": "Exponents and Logarithms",
    "csqrtl": "Exponents and Logarithms",
    "ctan": "Trig Functions",
    "ctanf": "Trig Functions",
    "ctanfN": "Trig Functions",
    "ctanfNx": "Trig Functions",
    "ctanh": "Hyperbolic Functions",
    "ctanhf": "Hyperbolic Functions",
    "ctanhfN": "Hyperbolic Functions",
    "ctanhfNx": "Hyperbolic Functions",
    "ctanhl": "Hyperbolic Functions",
    "ctanl": "Trig Functions",
    "ctermid": "Identifying the Terminal",
    "ctime": "Formatting Calendar Time",
    "ctime_r": "Formatting Calendar Time",
    "cuserid": "Who Logged In",
    "daddl": "Misc FP Arithmetic",
    "dcgettext": "Translation with gettext",
    "dcngettext": "Advanced gettext functions",
    "ddivl": "Misc FP Arithmetic",
    "dgettext": "Translation with gettext",
    "difftime": "Calculating Elapsed Time",
    "dirfd": "Opening a Directory",
    "dirname": "Finding Tokens in a String",
    "div": "Integer Division",
    "dmull": "Misc FP Arithmetic",
    "dngettext": "Advanced gettext functions",
    "drand48": "SVID Random",
    "drand48_r": "SVID Random",
    "drem": "Remainder Functions",
    "dremf": "Remainder Functions",
    "dreml": "Remainder Functions",
    "dsubl": "Misc FP Arithmetic",
    "DTTOIF": "Directory Entries",
    "dup": "Duplicating Descriptors",
    "dup2": "Duplicating Descriptors",
    "ecvt": "System V Number Conversion",
    "ecvt_r": "System V Number Conversion",
    "endfsent": "fstab",
    "endgrent": "Scanning All Groups",
    "endhostent": "Host Names",
    "endmntent": "mtab",
    "endnetent": "Networks Database",
    "endnetgrent": "Lookup Netgroup",
    "endprotoent": "Protocols Database",
    "endpwent": "Scanning All Users",
    "endservent": "Services Database",
    "endutent": "Manipulating the Database",
    "endutxent": "XPG Functions",
    "envz_add": "Envz Functions",
    "envz_entry": "Envz Functions",
    "envz_get": "Envz Functions",
    "envz_merge": "Envz Functions",
    "envz_remove": "Envz Functions",
    "envz_strip": "Envz Functions",
    "erand48": "SVID Random",
    "erand48_r": "SVID Random",
    "erf": "Special Functions",
    "erfc": "Special Functions",
    "erfcf": "Special Functions",
    "erfcfN": "Special Functions",
    "erfcfNx": "Special Functions",
    "erfcl": "Special Functions",
    "erff": "Special Functions",
    "erffN": "Special Functions",
    "erffNx": "Special Functions",
    "erfl": "Special Functions",
    "err": "Error Messages",
    "error": "Error Messages",
    "error_at_line": "Error Messages",
    "errx": "Error Messages",
    "execl": "Executing a File",
    "execle": "Executing a File",
    "execlp": "Executing a File",
    "execv": "Executing a File",
    "execve": "Executing a File",
    "execvp": "Executing a File",
    "exit": "Normal Termination",
    "exp": "Exponents and Logarithms",
    "exp10": "Exponents and Logarithms",
    "exp10f": "Exponents and Logarithms",
    "exp10fN": "Exponents and Logarithms",
    "exp10fNx": "Exponents and Logarithms",
    "exp10l": "Exponents and Logarithms",
    "exp2": "Exponents and Logarithms",
    "exp2f": "Exponents and Logarithms",
    "exp2fN": "Exponents and Logarithms",
    "exp2fNx": "Exponents and Logarithms",
    "exp2l": "Exponents and Logarithms",
    "expf": "Exponents and Logarithms",
    "expfN": "Exponents and Logarithms",
    "expfNx": "Exponents and Logarithms",
    "expl": "Exponents and Logarithms",
    "explicit_bzero": "Erasing Sensitive Data",
    "expm1": "Exponents and Logarithms",
    "expm1f": "Exponents and Logarithms",
    "expm1fN": "Exponents and Logarithms",
    "expm1fNx": "Exponents and Logarithms",
    "expm1l": "Exponents and Logarithms",
    "fabs": "Absolute Value",
    "fabsf": "Absolute Value",
    "fabsfN": "Absolute Value",
    "fabsfNx": "Absolute Value",
    "fabsl": "Absolute Value",
    "fadd": "Misc FP Arithmetic",
    "faddl": "Misc FP Arithmetic",
    "fchdir": "Working Directory",
    "fchmod": "Setting Permissions",
    "fchown": "File Owner",
    "fclose": "Closing Streams",
    "fcloseall": "Closing Streams",
    "fcntl": "Control Operations",
    "fcvt": "System V Number Conversion",
    "fcvt_r": "System V Number Conversion",
    "fdatasync": "Synchronizing I/O",
    "fdim": "Misc FP Arithmetic",
    "fdimf": "Misc FP Arithmetic",
    "fdimfN": "Misc FP Arithmetic",
    "fdimfNx": "Misc FP Arithmetic",
    "fdiml": "Misc FP Arithmetic",
    "fdiv": "Misc FP Arithmetic",
    "fdivl": "Misc FP Arithmetic",
    "fdopen": "Descriptors and Streams",
    "fdopendir": "Opening a Directory",
    "FD_CLR": "Waiting for I/O",
    "FD_ISSET": "Waiting for I/O",
    "FD_SET": "Waiting for I/O",
    "FD_ZERO": "Waiting for I/O",
    "feclearexcept": "Status bit operations",
    "fedisableexcept": "Control Functions",
    "feenableexcept": "Control Functions",
    "fegetenv": "Control Functions",
    "fegetexcept": "Control Functions",
    "fegetexceptflag": "Status bit operations",
    "fegetmode": "Control Functions",
    "fegetround": "Rounding",
    "feholdexcept": "Control Functions",
    "feof": "EOF and Errors",
    "feof_unlocked": "EOF and Errors",
    "feraiseexcept": "Status bit operations",
    "ferror": "EOF and Errors",
    "ferror_unlocked": "EOF and Errors",
    "fesetenv": "Control Functions",
    "fesetexcept": "Status bit operations",
    "fesetexceptflag": "Status bit operations",
    "fesetmode": "Control Functions",
    "fesetround": "Rounding",
    "fetestexcept": "Status bit operations",
    "fetestexceptflag": "Status bit operations",
    "feupdateenv": "Control Functions",
    "fflush": "Flushing Buffers",
    "fflush_unlocked": "Flushing Buffers",
    "fgetc": "Character Input",
    "fgetc_unlocked": "Character Input",
    "fgetgrent": "Scanning All Groups",
    "fgetgrent_r": "Scanning All Groups",
    "fgetpos": "Portable Positioning",
    "fgetpos64": "Portable Positioning",
    "fgetpwent": "Scanning All Users",
    "fgetpwent_r": "Scanning All Users",
    "fgets": "Line Input",
    "fgets_unlocked": "Line Input",
    "fgetwc": "Character Input",
    "fgetwc_unlocked": "Character Input",
    "fgetws": "Line Input",
    "fgetws_unlocked": "Line Input",
    "fileno": "Descriptors and Streams",
    "fileno_unlocked": "Descriptors and Streams",
    "finite": "Floating Point Classes",
    "finitef": "Floating Point Classes",
    "finitel": "Floating Point Classes",
    "flockfile": "Streams and Threads",
    "floor": "Rounding Functions",
    "floorf": "Rounding Functions",
    "floorfN": "Rounding Functions",
    "floorfNx": "Rounding Functions",
    "floorl": "Rounding Functions",
    "fma": "Misc FP Arithmetic",
    "fMaddfN": "Misc FP Arithmetic",
    "fMaddfNx": "Misc FP Arithmetic",
    "fmaf": "Misc FP Arithmetic",
    "fmafN": "Misc FP Arithmetic",
    "fmafNx": "Misc FP Arithmetic",
    "fmal": "Misc FP Arithmetic",
    "fmax": "Misc FP Arithmetic",
    "fmaxf": "Misc FP Arithmetic",
    "fmaxfN": "Misc FP Arithmetic",
    "fmaxfNx": "Misc FP Arithmetic",
    "fmaxl": "Misc FP Arithmetic",
    "fmaxmag": "Misc FP Arithmetic",
    "fmaxmagf": "Misc FP Arithmetic",
    "fmaxmagfN": "Misc FP Arithmetic",
    "fmaxmagfNx": "Misc FP Arithmetic",
    "fmaxmagl": "Misc FP Arithmetic",
    "fMdivfN": "Misc FP Arithmetic",
    "fMdivfNx": "Misc FP Arithmetic",
    "fmemopen": "String Streams",
    "fmin": "Misc FP Arithmetic",
    "fminf": "Misc FP Arithmetic",
    "fminfN": "Misc FP Arithmetic",
    "fminfNx": "Misc FP Arithmetic",
    "fminl": "Misc FP Arithmetic",
    "fminmag": "Misc FP Arithmetic",
    "fminmagf": "Misc FP Arithmetic",
    "fminmagfN": "Misc FP Arithmetic",
    "fminmagfNx": "Misc FP Arithmetic",
    "fminmagl": "Misc FP Arithmetic",
    "fMmulfN": "Misc FP Arithmetic",
    "fMmulfNx": "Misc FP Arithmetic",
    "fmod": "Remainder Functions",
    "fmodf": "Remainder Functions",
    "fmodfN": "Remainder Functions",
    "fmodfNx": "Remainder Functions",
    "fmodl": "Remainder Functions",
    "fMsubfN": "Misc FP Arithmetic",
    "fMsubfNx": "Misc FP Arithmetic",
    "fmtmsg": "Printing Formatted Messages",
    "fmul": "Misc FP Arithmetic",
    "fmull": "Misc FP Arithmetic",
    "fMxaddfN": "Misc FP Arithmetic",
    "fMxaddfNx": "Misc FP Arithmetic",
    "fMxdivfN": "Misc FP Arithmetic",
    "fMxdivfNx": "Misc FP Arithmetic",
    "fMxmulfN": "Misc FP Arithmetic",
    "fMxmulfNx": "Misc FP Arithmetic",
    "fMxsubfN": "Misc FP Arithmetic",
    "fMxsubfNx": "Misc FP Arithmetic",
    "fnmatch": "Wildcard Matching",
    "fopen": "Opening Streams",
    "fopen64": "Opening Streams",
    "fopencookie": "Streams and Cookies",
    "fork": "Creating a Process",
    "forkpty": "Pseudo-Terminal Pairs",
    "fpathconf": "Pathconf",
    "fpclassify": "Floating Point Classes",
    "fprintf": "Formatted Output Functions",
    "fputc": "Simple Output",
    "fputc_unlocked": "Simple Output",
    "fputs": "Simple Output",
    "fputs_unlocked": "Simple Output",
    "fputwc": "Simple Output",
    "fputwc_unlocked": "Simple Output",
    "fputws": "Simple Output",
    "fputws_unlocked": "Simple Output",
    "fread": "Block Input/Output",
    "fread_unlocked": "Block Input/Output",
    "free": "Freeing after Malloc",
    "freopen": "Opening Streams",
    "freopen64": "Opening Streams",
    "frexp": "Normalization Functions",
    "frexpf": "Normalization Functions",
    "frexpfN": "Normalization Functions",
    "frexpfNx": "Normalization Functions",
    "frexpl": "Normalization Functions",
    "fromfp": "Rounding Functions",
    "fromfpf": "Rounding Functions",
    "fromfpfN": "Rounding Functions",
    "fromfpfNx": "Rounding Functions",
    "fromfpl": "Rounding Functions",
    "fromfpx": "Rounding Functions",
    "fromfpxf": "Rounding Functions",
    "fromfpxfN": "Rounding Functions",
    "fromfpxfNx": "Rounding Functions",
    "fromfpxl": "Rounding Functions",
    "fscanf": "Formatted Input Functions",
    "fseek": "File Positioning",
    "fseeko": "File Positioning",
    "fseeko64": "File Positioning",
    "fsetpos": "Portable Positioning",
    "fsetpos64": "Portable Positioning",
    "fstat": "Reading Attributes",
    "fstat64": "Reading Attributes",
    "fsub": "Misc FP Arithmetic",
    "fsubl": "Misc FP Arithmetic",
    "fsync": "Synchronizing I/O",
    "ftell": "File Positioning",
    "ftello": "File Positioning",
    "ftello64": "File Positioning",
    "ftruncate": "File Size",
    "ftruncate64": "File Size",
    "ftrylockfile": "Streams and Threads",
    "ftw": "Working with Directory Trees",
    "ftw64": "Working with Directory Trees",
    "funlockfile": "Streams and Threads",
    "futimes": "File Times",
    "fwide": "Streams and I18N",
    "fwprintf": "Formatted Output Functions",
    "fwrite": "Block Input/Output",
    "fwrite_unlocked": "Block Input/Output",
    "fwscanf": "Formatted Input Functions",
    "gamma": "Special Functions",
    "gammaf": "Special Functions",
    "gammal": "Special Functions",
    "gcvt": "System V Number Conversion",
    "getauxval": "Auxiliary Vector",
    "getc": "Character Input",
    "getchar": "Character Input",
    "getchar_unlocked": "Character Input",
    "getcontext": "System V contexts",
    "getcpu": "CPU Affinity",
    "getcwd": "Working Directory",
    "getc_unlocked": "Character Input",
    "getdate": "General Time String Parsing",
    "getdate_r": "General Time String Parsing",
    "getdelim": "Line Input",
    "getdents64": "Low-level Directory Access",
    "getdomainnname": "Host Identification",
    "getegid": "Reading Persona",
    "getentropy": "Unpredictable Bytes",
    "getenv": "Environment Access",
    "geteuid": "Reading Persona",
    "getfsent": "fstab",
    "getfsfile": "fstab",
    "getfsspec": "fstab",
    "getgid": "Reading Persona",
    "getgrent": "Scanning All Groups",
    "getgrent_r": "Scanning All Groups",
    "getgrgid": "Lookup Group",
    "getgrgid_r": "Lookup Group",
    "getgrnam": "Lookup Group",
    "getgrnam_r": "Lookup Group",
    "getgrouplist": "Setting Groups",
    "getgroups": "Reading Persona",
    "gethostbyaddr": "Host Names",
    "gethostbyaddr_r": "Host Names",
    "gethostbyname": "Host Names",
    "gethostbyname2": "Host Names",
    "gethostbyname2_r": "Host Names",
    "gethostbyname_r": "Host Names",
    "gethostent": "Host Names",
    "gethostid": "Host Identification",
    "gethostname": "Host Identification",
    "getitimer": "Setting an Alarm",
    "getline": "Line Input",
    "getloadavg": "Processor Resources",
    "getlogin": "Who Logged In",
    "getmntent": "mtab",
    "getmntent_r": "mtab",
    "getnetbyaddr": "Networks Database",
    "getnetbyname": "Networks Database",
    "getnetent": "Networks Database",
    "getnetgrent": "Lookup Netgroup",
    "getnetgrent_r": "Lookup Netgroup",
    "getopt": "Using Getopt",
    "getopt_long": "Getopt Long Options",
    "getopt_long_only": "Getopt Long Options",
    "getpagesize": "Query Memory Parameters",
    "getpass": "getpass",
    "getpayload": "FP Bit Twiddling",
    "getpayloadf": "FP Bit Twiddling",
    "getpayloadfN": "FP Bit Twiddling",
    "getpayloadfNx": "FP Bit Twiddling",
    "getpayloadl": "FP Bit Twiddling",
    "getpeername": "Who is Connected",
    "getpgid": "Process Group Functions",
    "getpgrp": "Process Group Functions",
    "getpid": "Process Identification",
    "getppid": "Process Identification",
    "getpriority": "Traditional Scheduling Functions",
    "getprotobyname": "Protocols Database",
    "getprotobynumber": "Protocols Database",
    "getprotoent": "Protocols Database",
    "getpt": "Allocation",
    "getpwent": "Scanning All Users",
    "getpwent_r": "Scanning All Users",
    "getpwnam": "Lookup User",
    "getpwnam_r": "Lookup User",
    "getpwuid": "Lookup User",
    "getpwuid_r": "Lookup User",
    "getrandom": "Unpredictable Bytes",
    "getrlimit": "Limits on Resources",
    "getrlimit64": "Limits on Resources",
    "getrusage": "Resource Usage",
    "gets": "Line Input",
    "getservbyname": "Services Database",
    "getservbyport": "Services Database",
    "getservent": "Services Database",
    "getsid": "Process Group Functions",
    "getsockname": "Reading Address",
    "getsockopt": "Socket Option Functions",
    "getsubopt": "Suboptions",
    "gettext": "Translation with gettext",
    "gettid": "Process Identification",
    "gettimeofday": "Getting the Time",
    "getuid": "Reading Persona",
    "getumask": "Setting Permissions",
    "getutent": "Manipulating the Database",
    "getutent_r": "Manipulating the Database",
    "getutid": "Manipulating the Database",
    "getutid_r": "Manipulating the Database",
    "getutline": "Manipulating the Database",
    "getutline_r": "Manipulating the Database",
    "getutmp": "XPG Functions",
    "getutmpx": "XPG Functions",
    "getutxent": "XPG Functions",
    "getutxid": "XPG Functions",
    "getutxline": "XPG Functions",
    "getw": "Character Input",
    "getwc": "Character Input",
    "getwchar": "Character Input",
    "getwchar_unlocked": "Character Input",
    "getwc_unlocked": "Character Input",
    "getwd": "Working Directory",
    "get_avphys_pages": "Query Memory Parameters",
    "get_current_dir_name": "Working Directory",
    "get_nprocs": "Processor Resources",
    "get_nprocs_conf": "Processor Resources",
    "get_phys_pages": "Query Memory Parameters",
    "glob": "Calling Glob",
    "glob64": "Calling Glob",
    "globfree": "More Flags for Globbing",
    "globfree64": "More Flags for Globbing",
    "gmtime": "Broken-down Time",
    "gmtime_r": "Broken-down Time",
    "grantpt": "Allocation",
    "grantpt": "Configuring and compiling",
    "gsignal": "Signaling Yourself",
    "gtty": "BSD Terminal Modes",
    "hasmntopt": "mtab",
    "hcreate": "Hash Search Function",
    "hcreate_r": "Hash Search Function",
    "hdestroy": "Hash Search Function",
    "hdestroy_r": "Hash Search Function",
    "hsearch": "Hash Search Function",
    "hsearch_r": "Hash Search Function",
    "htonl": "Byte Order",
    "htons": "Byte Order",
    "hypot": "Exponents and Logarithms",
    "hypotf": "Exponents and Logarithms",
    "hypotfN": "Exponents and Logarithms",
    "hypotfNx": "Exponents and Logarithms",
    "hypotl": "Exponents and Logarithms",
    "iconv": "Generic Conversion Interface",
    "iconv_close": "Generic Conversion Interface",
    "iconv_open": "Generic Conversion Interface",
    "IFTODT": "Directory Entries",
    "if_freenameindex": "Interface Naming",
    "if_indextoname": "Interface Naming",
    "if_nameindex": "Interface Naming",
    "if_nametoindex": "Interface Naming",
    "ilogb": "Exponents and Logarithms",
    "ilogbf": "Exponents and Logarithms",
    "ilogbfN": "Exponents and Logarithms",
    "ilogbfNx": "Exponents and Logarithms",
    "ilogbl": "Exponents and Logarithms",
    "imaxabs": "Absolute Value",
    "imaxdiv": "Integer Division",
    "index": "Search Functions",
    "inet_addr": "Host Address Functions",
    "inet_aton": "Host Address Functions",
    "inet_lnaof": "Host Address Functions",
    "inet_makeaddr": "Host Address Functions",
    "inet_netof": "Host Address Functions",
    "inet_network": "Host Address Functions",
    "inet_ntoa": "Host Address Functions",
    "inet_ntop": "Host Address Functions",
    "inet_pton": "Host Address Functions",
    "initgroups": "Setting Groups",
    "initstate": "BSD Random",
    "initstate_r": "BSD Random",
    "innetgr": "Netgroup Membership",
    "ioctl": "IOCTLs",
    "isalnum": "Classification of Characters",
    "isalpha": "Classification of Characters",
    "isascii": "Classification of Characters",
    "isatty": "Is It a Terminal",
    "isblank": "Classification of Characters",
    "iscanonical": "Floating Point Classes",
    "iscntrl": "Classification of Characters",
    "isdigit": "Classification of Characters",
    "iseqsig": "FP Comparison Functions",
    "isfinite": "Floating Point Classes",
    "isgraph": "Classification of Characters",
    "isgreater": "FP Comparison Functions",
    "isgreaterequal": "FP Comparison Functions",
    "isinf": "Floating Point Classes",
    "isinff": "Floating Point Classes",
    "isinfl": "Floating Point Classes",
    "isless": "FP Comparison Functions",
    "islessequal": "FP Comparison Functions",
    "islessgreater": "FP Comparison Functions",
    "islower": "Classification of Characters",
    "isnan": "Floating Point Classes",
    "isnan": "Floating Point Classes",
    "isnanf": "Floating Point Classes",
    "isnanl": "Floating Point Classes",
    "isnormal": "Floating Point Classes",
    "isprint": "Classification of Characters",
    "ispunct": "Classification of Characters",
    "issignaling": "Floating Point Classes",
    "isspace": "Classification of Characters",
    "issubnormal": "Floating Point Classes",
    "isunordered": "FP Comparison Functions",
    "isupper": "Classification of Characters",
    "iswalnum": "Classification of Wide Characters",
    "iswalpha": "Classification of Wide Characters",
    "iswblank": "Classification of Wide Characters",
    "iswcntrl": "Classification of Wide Characters",
    "iswctype": "Classification of Wide Characters",
    "iswdigit": "Classification of Wide Characters",
    "iswgraph": "Classification of Wide Characters",
    "iswlower": "Classification of Wide Characters",
    "iswprint": "Classification of Wide Characters",
    "iswpunct": "Classification of Wide Characters",
    "iswspace": "Classification of Wide Characters",
    "iswupper": "Classification of Wide Characters",
    "iswxdigit": "Classification of Wide Characters",
    "isxdigit": "Classification of Characters",
    "iszero": "Floating Point Classes",
    "j0": "Special Functions",
    "j0f": "Special Functions",
    "j0fN": "Special Functions",
    "j0fNx": "Special Functions",
    "j0l": "Special Functions",
    "j1": "Special Functions",
    "j1f": "Special Functions",
    "j1fN": "Special Functions",
    "j1fNx": "Special Functions",
    "j1l": "Special Functions",
    "jn": "Special Functions",
    "jnf": "Special Functions",
    "jnfN": "Special Functions",
    "jnfNx": "Special Functions",
    "jnl": "Special Functions",
    "jrand48": "SVID Random",
    "jrand48_r": "SVID Random",
    "kill": "Signaling Another Process",
    "killpg": "Signaling Another Process",
    "l64a": "Encode Binary Data",
    "labs": "Absolute Value",
    "lcong48": "SVID Random",
    "lcong48_r": "SVID Random",
    "ldexp": "Normalization Functions",
    "ldexpf": "Normalization Functions",
    "ldexpfN": "Normalization Functions",
    "ldexpfNx": "Normalization Functions",
    "ldexpl": "Normalization Functions",
    "ldiv": "Integer Division",
    "lfind": "Array Search Function",
    "lgamma": "Special Functions",
    "lgammaf": "Special Functions",
    "lgammafN": "Special Functions",
    "lgammafNx": "Special Functions",
    "lgammafNx_r": "Special Functions",
    "lgammafN_r": "Special Functions",
    "lgammaf_r": "Special Functions",
    "lgammal": "Special Functions",
    "lgammal_r": "Special Functions",
    "lgamma_r": "Special Functions",
    "link": "Hard Links",
    "linkat": "Hard Links",
    "lio_listio": "Asynchronous Reads/Writes",
    "lio_listio64": "Asynchronous Reads/Writes",
    "listen": "Listening",
    "llabs": "Absolute Value",
    "lldiv": "Integer Division",
    "llogb": "Exponents and Logarithms",
    "llogbf": "Exponents and Logarithms",
    "llogbfN": "Exponents and Logarithms",
    "llogbfNx": "Exponents and Logarithms",
    "llogbl": "Exponents and Logarithms",
    "llrint": "Rounding Functions",
    "llrintf": "Rounding Functions",
    "llrintfN": "Rounding Functions",
    "llrintfNx": "Rounding Functions",
    "llrintl": "Rounding Functions",
    "llround": "Rounding Functions",
    "llroundf": "Rounding Functions",
    "llroundfN": "Rounding Functions",
    "llroundfNx": "Rounding Functions",
    "llroundl": "Rounding Functions",
    "localeconv": "The Lame Way to Locale Data",
    "localtime": "Broken-down Time",
    "localtime_r": "Broken-down Time",
    "log": "Exponents and Logarithms",
    "log10": "Exponents and Logarithms",
    "log10f": "Exponents and Logarithms",
    "log10fN": "Exponents and Logarithms",
    "log10fNx": "Exponents and Logarithms",
    "log10l": "Exponents and Logarithms",
    "log1p": "Exponents and Logarithms",
    "log1pf": "Exponents and Logarithms",
    "log1pfN": "Exponents and Logarithms",
    "log1pfNx": "Exponents and Logarithms",
    "log1pl": "Exponents and Logarithms",
    "log2": "Exponents and Logarithms",
    "log2f": "Exponents and Logarithms",
    "log2fN": "Exponents and Logarithms",
    "log2fNx": "Exponents and Logarithms",
    "log2l": "Exponents and Logarithms",
    "logb": "Exponents and Logarithms",
    "logbf": "Exponents and Logarithms",
    "logbfN": "Exponents and Logarithms",
    "logbfNx": "Exponents and Logarithms",
    "logbl": "Exponents and Logarithms",
    "logf": "Exponents and Logarithms",
    "logfN": "Exponents and Logarithms",
    "logfNx": "Exponents and Logarithms",
    "login": "Logging In and Out",
    "login_tty": "Logging In and Out",
    "logl": "Exponents and Logarithms",
    "logout": "Logging In and Out",
    "logwtmp": "Logging In and Out",
    "longjmp": "Non-Local Details",
    "lrand48": "SVID Random",
    "lrand48_r": "SVID Random",
    "lrint": "Rounding Functions",
    "lrintf": "Rounding Functions",
    "lrintfN": "Rounding Functions",
    "lrintfNx": "Rounding Functions",
    "lrintl": "Rounding Functions",
    "lround": "Rounding Functions",
    "lroundf": "Rounding Functions",
    "lroundfN": "Rounding Functions",
    "lroundfNx": "Rounding Functions",
    "lroundl": "Rounding Functions",
    "lsearch": "Array Search Function",
    "lseek": "File Position Primitive",
    "lseek64": "File Position Primitive",
    "lstat": "Reading Attributes",
    "lstat64": "Reading Attributes",
    "lutimes": "File Times",
    "madvise": "Memory-mapped I/O",
    "main": "Program Arguments",
    "makecontext": "System V contexts",
    "mallinfo": "Statistics of Malloc",
    "malloc": "Basic Allocation",
    "mallopt": "Malloc Tunable Parameters",
    "mblen": "Non-reentrant Character Conversion",
    "mbrlen": "Converting a Character",
    "mbrtowc": "Converting a Character",
    "mbsinit": "Keeping the state",
    "mbsnrtowcs": "Converting Strings",
    "mbsrtowcs": "Converting Strings",
    "mbstowcs": "Non-reentrant String Conversion",
    "mbtowc": "Non-reentrant Character Conversion",
    "mcheck": "Heap Consistency Checking",
    "memalign": "Aligned Memory Blocks",
    "memccpy": "Copying Strings and Arrays",
    "memchr": "Search Functions",
    "memcmp": "String/Array Comparison",
    "memcpy": "Copying Strings and Arrays",
    "memfd_create": "Memory-mapped I/O",
    "memfrob": "Obfuscating Data",
    "memmem": "Search Functions",
    "memmove": "Copying Strings and Arrays",
    "mempcpy": "Copying Strings and Arrays",
    "memrchr": "Search Functions",
    "memset": "Copying Strings and Arrays",
    "merge": "Actions in the NSS configuration",
    "mkdir": "Creating Directories",
    "mkdtemp": "Temporary Files",
    "mkfifo": "FIFO Special Files",
    "mknod": "Making Special Files",
    "mkstemp": "Temporary Files",
    "mktemp": "Temporary Files",
    "mktime": "Broken-down Time",
    "mlock": "Page Lock Functions",
    "mlock2": "Page Lock Functions",
    "mlockall": "Page Lock Functions",
    "mmap": "Memory-mapped I/O",
    "mmap64": "Memory-mapped I/O",
    "modf": "Rounding Functions",
    "modff": "Rounding Functions",
    "modffN": "Rounding Functions",
    "modffNx": "Rounding Functions",
    "modfl": "Rounding Functions",
    "mount": "Mount-Unmount-Remount",
    "mprobe": "Heap Consistency Checking",
    "mprotect": "Memory Protection",
    "mrand48": "SVID Random",
    "mrand48_r": "SVID Random",
    "mremap": "Memory-mapped I/O",
    "msync": "Memory-mapped I/O",
    "mtrace": "Tracing malloc",
    "mtx_destroy": "ISO C Mutexes",
    "mtx_init": "ISO C Mutexes",
    "mtx_lock": "ISO C Mutexes",
    "mtx_timedlock": "ISO C Mutexes",
    "mtx_trylock": "ISO C Mutexes",
    "mtx_unlock": "ISO C Mutexes",
    "munlock": "Page Lock Functions",
    "munlockall": "Page Lock Functions",
    "munmap": "Memory-mapped I/O",
    "muntrace": "Tracing malloc",
    "nan": "FP Bit Twiddling",
    "nanf": "FP Bit Twiddling",
    "nanfN": "FP Bit Twiddling",
    "nanfNx": "FP Bit Twiddling",
    "nanl": "FP Bit Twiddling",
    "nanosleep": "Sleeping",
    "nearbyint": "Rounding Functions",
    "nearbyintf": "Rounding Functions",
    "nearbyintfN": "Rounding Functions",
    "nearbyintfNx": "Rounding Functions",
    "nearbyintl": "Rounding Functions",
    "nextafter": "FP Bit Twiddling",
    "nextafterf": "FP Bit Twiddling",
    "nextafterfN": "FP Bit Twiddling",
    "nextafterfNx": "FP Bit Twiddling",
    "nextafterl": "FP Bit Twiddling",
    "nextdown": "FP Bit Twiddling",
    "nextdownf": "FP Bit Twiddling",
    "nextdownfN": "FP Bit Twiddling",
    "nextdownfNx": "FP Bit Twiddling",
    "nextdownl": "FP Bit Twiddling",
    "nexttoward": "FP Bit Twiddling",
    "nexttowardf": "FP Bit Twiddling",
    "nexttowardl": "FP Bit Twiddling",
    "nextup": "FP Bit Twiddling",
    "nextupf": "FP Bit Twiddling",
    "nextupfN": "FP Bit Twiddling",
    "nextupfNx": "FP Bit Twiddling",
    "nextupl": "FP Bit Twiddling",
    "nftw": "Working with Directory Trees",
    "nftw64": "Working with Directory Trees",
    "ngettext": "Advanced gettext functions",
    "nice": "Traditional Scheduling Functions",
    "nl_langinfo": "The Elegant and Fast Way",
    "notfound": "Actions in the NSS configuration",
    "nrand48": "SVID Random",
    "nrand48_r": "SVID Random",
    "ntohl": "Byte Order",
    "ntohs": "Byte Order",
    "ntp_adjtime": "Setting and Adjusting the Time",
    "ntp_gettime": "Setting and Adjusting the Time",
    "obstack_1grow": "Growing Objects",
    "obstack_1grow_fast": "Extra Fast Growing",
    "obstack_alignment_mask": "Obstacks Data Alignment",
    "obstack_alloc": "Allocation in an Obstack",
    "obstack_base": "Status of an Obstack",
    "obstack_blank": "Growing Objects",
    "obstack_blank_fast": "Extra Fast Growing",
    "obstack_chunk_alloc": "Preparing for Obstacks",
    "obstack_chunk_free": "Preparing for Obstacks",
    "obstack_chunk_size": "Obstack Chunks",
    "obstack_copy": "Allocation in an Obstack",
    "obstack_copy0": "Allocation in an Obstack",
    "obstack_finish": "Growing Objects",
    "obstack_free": "Freeing Obstack Objects",
    "obstack_grow": "Growing Objects",
    "obstack_grow0": "Growing Objects",
    "obstack_init": "Preparing for Obstacks",
    "obstack_int_grow": "Growing Objects",
    "obstack_int_grow_fast": "Extra Fast Growing",
    "obstack_next_free": "Status of an Obstack",
    "obstack_object_size": "Growing Objects",
    "obstack_object_size": "Status of an Obstack",
    "obstack_printf": "Dynamic Output",
    "obstack_ptr_grow": "Growing Objects",
    "obstack_ptr_grow_fast": "Extra Fast Growing",
    "obstack_room": "Extra Fast Growing",
    "obstack_vprintf": "Variable Arguments Output",
    "offsetof": "Structure Measurement",
    "on_exit": "Cleanups on Exit",
    "open": "Opening and Closing Files",
    "open64": "Opening and Closing Files",
    "opendir": "Opening a Directory",
    "openlog": "openlog",
    "openpty": "Pseudo-Terminal Pairs",
    "open_memstream": "String Streams",
    "parse_printf_format": "Parsing a Template String",
    "pathconf": "Pathconf",
    "pause": "Using Pause",
    "pclose": "Pipe to a Subprocess",
    "perror": "Error Messages",
    "pipe": "Creating a Pipe",
    "pkey_alloc": "Memory Protection",
    "pkey_free": "Memory Protection",
    "pkey_get": "Memory Protection",
    "pkey_mprotect": "Memory Protection",
    "pkey_set": "Memory Protection",
    "popen": "Pipe to a Subprocess",
    "posix_fallocate": "Storage Allocation",
    "posix_fallocate64": "Storage Allocation",
    "posix_memalign": "Aligned Memory Blocks",
    "pow": "Exponents and Logarithms",
    "powf": "Exponents and Logarithms",
    "powfN": "Exponents and Logarithms",
    "powfNx": "Exponents and Logarithms",
    "powl": "Exponents and Logarithms",
    "pread": "I/O Primitives",
    "pread64": "I/O Primitives",
    "preadv": "Scatter-Gather",
    "preadv2": "Scatter-Gather",
    "preadv64": "Scatter-Gather",
    "preadv64v2": "Scatter-Gather",
    "printf": "Formatted Output Functions",
    "printf_size": "Predefined Printf Handlers",
    "printf_size_info": "Predefined Printf Handlers",
    "psignal": "Signal Messages",
    "pthread_clockjoin_np": "Default Thread Attributes",
    "pthread_cond_clockwait": "Default Thread Attributes",
    "pthread_getattr_default_np": "Default Thread Attributes",
    "pthread_key_create": "Thread-specific Data",
    "pthread_key_delete": "Thread-specific Data",
    "pthread_rwlock_clockrdlock": "Default Thread Attributes",
    "pthread_rwlock_clockwrlock": "Default Thread Attributes",
    "pthread_setattr_default_np": "Default Thread Attributes",
    "pthread_setspecific": "Thread-specific Data",
    "pthread_timedjoin_np": "Default Thread Attributes",
    "pthread_tryjoin_np": "Default Thread Attributes",
    "ptsname": "Allocation",
    "ptsname_r": "Allocation",
    "putc": "Simple Output",
    "putchar": "Simple Output",
    "putchar_unlocked": "Simple Output",
    "putc_unlocked": "Simple Output",
    "putenv": "Environment Access",
    "putpwent": "Writing a User Entry",
    "puts": "Simple Output",
    "pututline": "Manipulating the Database",
    "pututxline": "XPG Functions",
    "putw": "Simple Output",
    "putwc": "Simple Output",
    "putwchar": "Simple Output",
    "putwchar_unlocked": "Simple Output",
    "putwc_unlocked": "Simple Output",
    "pwrite": "I/O Primitives",
    "pwrite64": "I/O Primitives",
    "pwritev": "Scatter-Gather",
    "pwritev2": "Scatter-Gather",
    "pwritev64": "Scatter-Gather",
    "pwritev64v2": "Scatter-Gather",
    "qecvt": "System V Number Conversion",
    "qecvt_r": "System V Number Conversion",
    "qfcvt": "System V Number Conversion",
    "qfcvt_r": "System V Number Conversion",
    "qgcvt": "System V Number Conversion",
    "qsort": "Array Sort Function",
    "raise": "Signaling Yourself",
    "rand": "ISO Random",
    "random": "BSD Random",
    "random_r": "BSD Random",
    "rand_r": "ISO Random",
    "rawmemchr": "Search Functions",
    "read": "I/O Primitives",
    "readdir": "Reading/Closing Directory",
    "readdir64": "Reading/Closing Directory",
    "readdir64_r": "Reading/Closing Directory",
    "readdir_r": "Reading/Closing Directory",
    "readlink": "Symbolic Links",
    "readv": "Scatter-Gather",
    "realloc": "Changing Block Size",
    "reallocarray": "Changing Block Size",
    "realpath": "Symbolic Links",
    "recv": "Receiving Data",
    "recvfrom": "Receiving Datagrams",
    "regcomp": "POSIX Regexp Compilation",
    "regerror": "Regexp Cleanup",
    "regexec": "Matching POSIX Regexps",
    "regfree": "Regexp Cleanup",
    "register_printf_function": "Registering New Conversions",
    "remainder": "Remainder Functions",
    "remainderf": "Remainder Functions",
    "remainderfN": "Remainder Functions",
    "remainderfNx": "Remainder Functions",
    "remainderl": "Remainder Functions",
    "remove": "Deleting Files",
    "rename": "Renaming Files",
    "return": "Actions in the NSS configuration",
    "rewind": "File Positioning",
    "rewinddir": "Random Access Directory",
    "rindex": "Search Functions",
    "rint": "Rounding Functions",
    "rintf": "Rounding Functions",
    "rintfN": "Rounding Functions",
    "rintfNx": "Rounding Functions",
    "rintl": "Rounding Functions",
    "rmdir": "Deleting Files",
    "round": "Rounding Functions",
    "roundeven": "Rounding Functions",
    "roundevenf": "Rounding Functions",
    "roundevenfN": "Rounding Functions",
    "roundevenfNx": "Rounding Functions",
    "roundevenl": "Rounding Functions",
    "roundf": "Rounding Functions",
    "roundfN": "Rounding Functions",
    "roundfNx": "Rounding Functions",
    "roundl": "Rounding Functions",
    "rpmatch": "Yes-or-No Questions",
    "scalb": "Normalization Functions",
    "scalbf": "Normalization Functions",
    "scalbl": "Normalization Functions",
    "scalbln": "Normalization Functions",
    "scalblnf": "Normalization Functions",
    "scalblnfN": "Normalization Functions",
    "scalblnfNx": "Normalization Functions",
    "scalblnl": "Normalization Functions",
    "scalbn": "Normalization Functions",
    "scalbnf": "Normalization Functions",
    "scalbnfN": "Normalization Functions",
    "scalbnfNx": "Normalization Functions",
    "scalbnl": "Normalization Functions",
    "scandir": "Scanning Directory Content",
    "scandir64": "Scanning Directory Content",
    "scanf": "Formatted Input Functions",
    "sched_getaffinity": "CPU Affinity",
    "sched_getparam": "Basic Scheduling Functions",
    "sched_getscheduler": "Basic Scheduling Functions",
    "sched_get_priority_max": "Basic Scheduling Functions",
    "sched_get_priority_min": "Basic Scheduling Functions",
    "sched_rr_get_interval": "Basic Scheduling Functions",
    "sched_setaffinity": "CPU Affinity",
    "sched_setparam": "Basic Scheduling Functions",
    "sched_setscheduler": "Basic Scheduling Functions",
    "sched_yield": "Basic Scheduling Functions",
    "secure_getenv": "Environment Access",
    "seed48": "SVID Random",
    "seed48_r": "SVID Random",
    "seekdir": "Random Access Directory",
    "select": "Waiting for I/O",
    "semctl": "Semaphores",
    "semget": "Semaphores",
    "semop": "Semaphores",
    "semtimedop": "Semaphores",
    "sem_clockwait": "Default Thread Attributes",
    "sem_close": "Semaphores",
    "sem_destroy": "Semaphores",
    "sem_getvalue": "Semaphores",
    "sem_init": "Semaphores",
    "sem_post": "Semaphores",
    "sem_timedwait": "Semaphores",
    "sem_trywait": "Semaphores",
    "sem_unlink": "Semaphores",
    "sem_wait": "Semaphores",
    "send": "Sending Data",
    "sendto": "Sending Datagrams",
    "setbuf": "Controlling Buffering",
    "setbuffer": "Controlling Buffering",
    "setcontext": "System V contexts",
    "setdomainname": "Host Identification",
    "setegid": "Setting Groups",
    "setenv": "Environment Access",
    "seteuid": "Setting User ID",
    "setfsent": "fstab",
    "setgid": "Setting Groups",
    "setgrent": "Scanning All Groups",
    "setgroups": "Setting Groups",
    "sethostent": "Host Names",
    "sethostid": "Host Identification",
    "sethostname": "Host Identification",
    "setitimer": "Setting an Alarm",
    "setjmp": "Non-Local Details",
    "setlinebuf": "Controlling Buffering",
    "setlocale": "Setting the Locale",
    "setlogmask": "setlogmask",
    "setmntent": "mtab",
    "setnetent": "Networks Database",
    "setnetgrent": "Lookup Netgroup",
    "setpayload": "FP Bit Twiddling",
    "setpayloadf": "FP Bit Twiddling",
    "setpayloadfN": "FP Bit Twiddling",
    "setpayloadfNx": "FP Bit Twiddling",
    "setpayloadl": "FP Bit Twiddling",
    "setpayloadsig": "FP Bit Twiddling",
    "setpayloadsigf": "FP Bit Twiddling",
    "setpayloadsigfN": "FP Bit Twiddling",
    "setpayloadsigfNx": "FP Bit Twiddling",
    "setpayloadsigl": "FP Bit Twiddling",
    "setpgid": "Process Group Functions",
    "setpgrp": "Process Group Functions",
    "setpriority": "Traditional Scheduling Functions",
    "setprotoent": "Protocols Database",
    "setpwent": "Scanning All Users",
    "setregid": "Setting Groups",
    "setreuid": "Setting User ID",
    "setrlimit": "Limits on Resources",
    "setrlimit64": "Limits on Resources",
    "setservent": "Services Database",
    "setsid": "Process Group Functions",
    "setsockopt": "Socket Option Functions",
    "setstate": "BSD Random",
    "setstate_r": "BSD Random",
    "settimeofday": "Setting and Adjusting the Time",
    "setuid": "Setting User ID",
    "setutent": "Manipulating the Database",
    "setutxent": "XPG Functions",
    "setvbuf": "Controlling Buffering",
    "shm_open": "Memory-mapped I/O",
    "shm_unlink": "Memory-mapped I/O",
    "shutdown": "Closing a Socket",
    "sigaction": "Advanced Signal Handling",
    "sigaddset": "Signal Sets",
    "sigaltstack": "Signal Stack",
    "sigblock": "BSD Signal Handling",
    "sigdelset": "Signal Sets",
    "sigemptyset": "Signal Sets",
    "sigfillset": "Signal Sets",
    "siginterrupt": "BSD Signal Handling",
    "sigismember": "Signal Sets",
    "siglongjmp": "Non-Local Exits and Signals",
    "sigmask": "BSD Signal Handling",
    "signal": "Basic Signal Handling",
    "signbit": "FP Bit Twiddling",
    "significand": "Normalization Functions",
    "significandf": "Normalization Functions",
    "significandl": "Normalization Functions",
    "sigpause": "BSD Signal Handling",
    "sigpending": "Checking for Pending Signals",
    "sigprocmask": "Process Signal Mask",
    "sigsetjmp": "Non-Local Exits and Signals",
    "sigsetmask": "BSD Signal Handling",
    "sigstack": "Signal Stack",
    "sigsuspend": "Sigsuspend",
    "sin": "Trig Functions",
    "sincos": "Trig Functions",
    "sincosf": "Trig Functions",
    "sincosfN": "Trig Functions",
    "sincosfNx": "Trig Functions",
    "sincosl": "Trig Functions",
    "sinf": "Trig Functions",
    "sinfN": "Trig Functions",
    "sinfNx": "Trig Functions",
    "sinh": "Hyperbolic Functions",
    "sinhf": "Hyperbolic Functions",
    "sinhfN": "Hyperbolic Functions",
    "sinhfNx": "Hyperbolic Functions",
    "sinhl": "Hyperbolic Functions",
    "sinl": "Trig Functions",
    "sleep": "Sleeping",
    "snprintf": "Formatted Output Functions",
    "socket": "Creating a Socket",
    "socketpair": "Socket Pairs",
    "sprintf": "Formatted Output Functions",
    "sqrt": "Exponents and Logarithms",
    "sqrtf": "Exponents and Logarithms",
    "sqrtfN": "Exponents and Logarithms",
    "sqrtfNx": "Exponents and Logarithms",
    "sqrtl": "Exponents and Logarithms",
    "srand": "ISO Random",
    "srand48": "SVID Random",
    "srand48_r": "SVID Random",
    "srandom": "BSD Random",
    "srandom_r": "BSD Random",
    "sscanf": "Formatted Input Functions",
    "ssignal": "Basic Signal Handling",
    "stat": "Reading Attributes",
    "stat64": "Reading Attributes",
    "stime": "Setting and Adjusting the Time",
    "stpcpy": "Copying Strings and Arrays",
    "stpncpy": "Truncating Strings",
    "strcasecmp": "String/Array Comparison",
    "strcasestr": "Search Functions",
    "strcat": "Concatenating Strings",
    "strchr": "Search Functions",
    "strchrnul": "Search Functions",
    "strcmp": "String/Array Comparison",
    "strcoll": "Collation Functions",
    "strcpy": "Copying Strings and Arrays",
    "strcspn": "Search Functions",
    "strdup": "Copying Strings and Arrays",
    "strdupa": "Copying Strings and Arrays",
    "strerror": "Error Messages",
    "strerror_r": "Error Messages",
    "strfmon": "Formatting Numbers",
    "strfromd": "Printing of Floats",
    "strfromf": "Printing of Floats",
    "strfromfN": "Printing of Floats",
    "strfromfNx": "Printing of Floats",
    "strfroml": "Printing of Floats",
    "strfry": "Shuffling Bytes",
    "strftime": "Formatting Calendar Time",
    "strlen": "String Length",
    "strncasecmp": "String/Array Comparison",
    "strncat": "Truncating Strings",
    "strncmp": "String/Array Comparison",
    "strncpy": "Truncating Strings",
    "strndup": "Truncating Strings",
    "strndupa": "Truncating Strings",
    "strnlen": "String Length",
    "strpbrk": "Search Functions",
    "strptime": "Low-Level Time String Parsing",
    "strrchr": "Search Functions",
    "strsep": "Finding Tokens in a String",
    "strsignal": "Signal Messages",
    "strspn": "Search Functions",
    "strstr": "Search Functions",
    "strtod": "Parsing of Floats",
    "strtof": "Parsing of Floats",
    "strtofN": "Parsing of Floats",
    "strtofNx": "Parsing of Floats",
    "strtoimax": "Parsing of Integers",
    "strtok": "Finding Tokens in a String",
    "strtok_r": "Finding Tokens in a String",
    "strtol": "Parsing of Integers",
    "strtold": "Parsing of Floats",
    "strtoll": "Parsing of Integers",
    "strtoq": "Parsing of Integers",
    "strtoul": "Parsing of Integers",
    "strtoull": "Parsing of Integers",
    "strtoumax": "Parsing of Integers",
    "strtouq": "Parsing of Integers",
    "strverscmp": "String/Array Comparison",
    "strxfrm": "Collation Functions",
    "stty": "BSD Terminal Modes",
    "success": "Actions in the NSS configuration",
    "SUN_LEN": "Local Namespace Details",
    "swapcontext": "System V contexts",
    "swprintf": "Formatted Output Functions",
    "swscanf": "Formatted Input Functions",
    "symlink": "Symbolic Links",
    "sync": "Synchronizing I/O",
    "syscall": "System Calls",
    "sysconf": "Sysconf Definition",
    "sysctl": "System Parameters",
    "syslog": "syslog; vsyslog",
    "system": "Running a Command",
    "sysv_signal": "Basic Signal Handling",
    "S_ISBLK": "Testing File Type",
    "S_ISCHR": "Testing File Type",
    "S_ISDIR": "Testing File Type",
    "S_ISFIFO": "Testing File Type",
    "S_ISLNK": "Testing File Type",
    "S_ISREG": "Testing File Type",
    "S_ISSOCK": "Testing File Type",
    "S_TYPEISMQ": "Testing File Type",
    "S_TYPEISSEM": "Testing File Type",
    "S_TYPEISSHM": "Testing File Type",
    "tan": "Trig Functions",
    "tanf": "Trig Functions",
    "tanfN": "Trig Functions",
    "tanfNx": "Trig Functions",
    "tanh": "Hyperbolic Functions",
    "tanhf": "Hyperbolic Functions",
    "tanhfN": "Hyperbolic Functions",
    "tanhfNx": "Hyperbolic Functions",
    "tanhl": "Hyperbolic Functions",
    "tanl": "Trig Functions",
    "tcdrain": "Line Control",
    "tcflow": "Line Control",
    "tcflush": "Line Control",
    "tcgetattr": "Mode Functions",
    "tcgetpgrp": "Terminal Access Functions",
    "tcgetsid": "Terminal Access Functions",
    "tcsendbreak": "Line Control",
    "tcsetattr": "Mode Functions",
    "tcsetpgrp": "Terminal Access Functions",
    "tdelete": "Tree Search Function",
    "tdestroy": "Tree Search Function",
    "telldir": "Random Access Directory",
    "tempnam": "Temporary Files",
    "TEMP_FAILURE_RETRY": "Interrupted Primitives",
    "textdomain": "Locating gettext catalog",
    "tfind": "Tree Search Function",
    "tgamma": "Special Functions",
    "tgammaf": "Special Functions",
    "tgammafN": "Special Functions",
    "tgammafNx": "Special Functions",
    "tgammal": "Special Functions",
    "tgkill": "Signaling Another Process",
    "thrd_create": "ISO C Thread Management",
    "thrd_current": "ISO C Thread Management",
    "thrd_detach": "ISO C Thread Management",
    "thrd_equal": "ISO C Thread Management",
    "thrd_exit": "ISO C Thread Management",
    "thrd_join": "ISO C Thread Management",
    "thrd_sleep": "ISO C Thread Management",
    "thrd_yield": "ISO C Thread Management",
    "time": "Getting the Time",
    "timegm": "Broken-down Time",
    "timelocal": "Broken-down Time",
    "times": "Processor Time",
    "tmpfile": "Temporary Files",
    "tmpfile64": "Temporary Files",
    "tmpnam": "Temporary Files",
    "tmpnam_r": "Temporary Files",
    "toascii": "Case Conversion",
    "tolower": "Case Conversion",
    "totalorder": "FP Comparison Functions",
    "totalorderf": "FP Comparison Functions",
    "totalorderfN": "FP Comparison Functions",
    "totalorderfNx": "FP Comparison Functions",
    "totalorderl": "FP Comparison Functions",
    "totalordermag": "FP Comparison Functions",
    "totalordermagf": "FP Comparison Functions",
    "totalordermagfN": "FP Comparison Functions",
    "totalordermagfNx": "FP Comparison Functions",
    "totalordermagl": "FP Comparison Functions",
    "toupper": "Case Conversion",
    "towctrans": "Wide Character Case Conversion",
    "towlower": "Wide Character Case Conversion",
    "towupper": "Wide Character Case Conversion",
    "trunc": "Rounding Functions",
    "truncate": "File Size",
    "truncate64": "File Size",
    "truncf": "Rounding Functions",
    "truncfN": "Rounding Functions",
    "truncfNx": "Rounding Functions",
    "truncl": "Rounding Functions",
    "tryagain": "Actions in the NSS configuration",
    "tsearch": "Tree Search Function",
    "tss_create": "ISO C Thread-local Storage",
    "tss_delete": "ISO C Thread-local Storage",
    "tss_get": "ISO C Thread-local Storage",
    "tss_set": "ISO C Thread-local Storage",
    "ttyname": "Is It a Terminal",
    "ttyname_r": "Is It a Terminal",
    "twalk": "Tree Search Function",
    "twalk_r": "Tree Search Function",
    "tzset": "Time Zone Functions",
    "ufromfp": "Rounding Functions",
    "ufromfpf": "Rounding Functions",
    "ufromfpfN": "Rounding Functions",
    "ufromfpfNx": "Rounding Functions",
    "ufromfpl": "Rounding Functions",
    "ufromfpx": "Rounding Functions",
    "ufromfpxf": "Rounding Functions",
    "ufromfpxfN": "Rounding Functions",
    "ufromfpxfNx": "Rounding Functions",
    "ufromfpxl": "Rounding Functions",
    "ulimit": "Limits on Resources",
    "umask": "Setting Permissions",
    "umount": "Mount-Unmount-Remount",
    "umount2": "Mount-Unmount-Remount",
    "uname": "Platform Type",
    "unavail": "Actions in the NSS configuration",
    "ungetc": "How Unread",
    "ungetwc": "How Unread",
    "unlink": "Deleting Files",
    "unlockpt": "Allocation",
    "unsetenv": "Environment Access",
    "updwtmp": "Manipulating the Database",
    "utime": "File Times",
    "utimes": "File Times",
    "utmpname": "Manipulating the Database",
    "utmpxname": "XPG Functions",
    "valloc": "Aligned Memory Blocks",
    "vasprintf": "Variable Arguments Output",
    "va_arg": "Argument Macros",
    "va_copy": "Argument Macros",
    "va_end": "Argument Macros",
    "va_start": "Argument Macros",
    "verr": "Error Messages",
    "verrx": "Error Messages",
    "versionsort": "Scanning Directory Content",
    "versionsort64": "Scanning Directory Content",
    "vfork": "Creating a Process",
    "vfprintf": "Variable Arguments Output",
    "vfscanf": "Variable Arguments Input",
    "vfwprintf": "Variable Arguments Output",
    "vfwscanf": "Variable Arguments Input",
    "vlimit": "Limits on Resources",
    "vprintf": "Variable Arguments Output",
    "vscanf": "Variable Arguments Input",
    "vsnprintf": "Variable Arguments Output",
    "vsprintf": "Variable Arguments Output",
    "vsscanf": "Variable Arguments Input",
    "vswprintf": "Variable Arguments Output",
    "vswscanf": "Variable Arguments Input",
    "vsyslog": "syslog; vsyslog",
    "vtimes": "Resource Usage",
    "vwarn": "Error Messages",
    "vwarnx": "Error Messages",
    "vwprintf": "Variable Arguments Output",
    "vwscanf": "Variable Arguments Input",
    "wait": "Process Completion",
    "wait3": "BSD Wait Functions",
    "wait4": "Process Completion",
    "waitpid": "Process Completion",
    "warn": "Error Messages",
    "warnx": "Error Messages",
    "WCOREDUMP": "Process Completion Status",
    "wcpcpy": "Copying Strings and Arrays",
    "wcpncpy": "Truncating Strings",
    "wcrtomb": "Converting a Character",
    "wcscasecmp": "String/Array Comparison",
    "wcscat": "Concatenating Strings",
    "wcschr": "Search Functions",
    "wcschrnul": "Search Functions",
    "wcscmp": "String/Array Comparison",
    "wcscoll": "Collation Functions",
    "wcscpy": "Copying Strings and Arrays",
    "wcscspn": "Search Functions",
    "wcsdup": "Copying Strings and Arrays",
    "wcsftime": "Formatting Calendar Time",
    "wcslen": "String Length",
    "wcsncasecmp": "String/Array Comparison",
    "wcsncat": "Truncating Strings",
    "wcsncmp": "String/Array Comparison",
    "wcsncpy": "Truncating Strings",
    "wcsnlen": "String Length",
    "wcsnrtombs": "Converting Strings",
    "wcspbrk": "Search Functions",
    "wcsrchr": "Search Functions",
    "wcsrtombs": "Converting Strings",
    "wcsspn": "Search Functions",
    "wcsstr": "Search Functions",
    "wcstod": "Parsing of Floats",
    "wcstof": "Parsing of Floats",
    "wcstofN": "Parsing of Floats",
    "wcstofNx": "Parsing of Floats",
    "wcstoimax": "Parsing of Integers",
    "wcstok": "Finding Tokens in a String",
    "wcstol": "Parsing of Integers",
    "wcstold": "Parsing of Floats",
    "wcstoll": "Parsing of Integers",
    "wcstombs": "Non-reentrant String Conversion",
    "wcstoq": "Parsing of Integers",
    "wcstoul": "Parsing of Integers",
    "wcstoull": "Parsing of Integers",
    "wcstoumax": "Parsing of Integers",
    "wcstouq": "Parsing of Integers",
    "wcswcs": "Search Functions",
    "wcsxfrm": "Collation Functions",
    "wctob": "Converting a Character",
    "wctomb": "Non-reentrant Character Conversion",
    "wctrans": "Wide Character Case Conversion",
    "wctype": "Classification of Wide Characters",
    "WEXITSTATUS": "Process Completion Status",
    "WIFEXITED": "Process Completion Status",
    "WIFSIGNALED": "Process Completion Status",
    "WIFSTOPPED": "Process Completion Status",
    "wmemchr": "Search Functions",
    "wmemcmp": "String/Array Comparison",
    "wmemcpy": "Copying Strings and Arrays",
    "wmemmove": "Copying Strings and Arrays",
    "wmempcpy": "Copying Strings and Arrays",
    "wmemset": "Copying Strings and Arrays",
    "wordexp": "Calling Wordexp",
    "wordfree": "Calling Wordexp",
    "wprintf": "Formatted Output Functions",
    "write": "I/O Primitives",
    "writev": "Scatter-Gather",
    "wscanf": "Formatted Input Functions",
    "WSTOPSIG": "Process Completion Status",
    "WTERMSIG": "Process Completion Status",
    "y0": "Special Functions",
    "y0f": "Special Functions",
    "y0fN": "Special Functions",
    "y0fNx": "Special Functions",
    "y0l": "Special Functions",
    "y1": "Special Functions",
    "y1f": "Special Functions",
    "y1fN": "Special Functions",
    "y1fNx": "Special Functions",
    "y1l": "Special Functions",
    "yn": "Special Functions",
    "ynf": "Special Functions",
    "ynfN": "Special Functions",
    "ynfNx": "Special Functions",
    "ynl": "Special Functions"
}
